### ISSUE TITLE
Neo4j improvements

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/trainbenchmark#65]
- [x] get the degree (number of relationships of both nodes for the type and direction) and use the smaller one as your search space @ https://github.com/FTSRG/trainbenchmark/blob/master/trainbenchmark-tool-neo4j/src/main/java/hu/bme/mit/trainbenchmark/benchmark/neo4j/util/Neo4jUtil.java#L11

**Comment by jexp** [comment]
Should only be done if both nodes are dense, if one node is not dense, then use that one.
