### ISSUE TITLE
Viatra inject Transformation different to Paper

### ISSUE THREAD

**Issue by otherwiseopen** [FTSRG/trainbenchmark#99]
In Viatra, the PosLength transformation does not set the length to 0 but to -oldLength+1. Because an inject match finds all segments, a match could be removed if the length is below 0 already.

https://github.com/FTSRG/trainbenchmark/blob/f265c9532b5016268f5d8aec7d08ac71eb900e4e/trainbenchmark-tool-viatra/src/main/java/hu/bme/mit/trainbenchmark/benchmark/viatra/transformations/inject/ViatraTransformationInjectPosLength.java#L30

**Comment by szarnyasg** [comment]
Well spotted -- thanks for reporting this! It's now fixed. I was wondering why the tests did not catch this: it turns out all 10 selected Segment had a positive length:

```java
System.out.println(match.getSegment().getLength());
```

```
837
635
932
559
382
137
648
573
328
843
```
